version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-stretch
    steps:
      - checkout

      - restore_cache:
          keys:
            - hyper-pane-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: hyper-pane-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      
      - run:
          name: Test
          command: yarn run test
